backend = "glx";

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-background-exclude = [
"class_g = 'tray'",
"class_g = 'Polybar'"
]

blur-method = "kawase";
blur-strength = 6;
